# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 13:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '食物分类',
                'verbose_name_plural': '食物分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=128, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='菜品名')),
                ('inro', ckeditor_uploader.fields.RichTextUploadingField(max_length=1024, verbose_name='菜品介绍')),
                ('produce', ckeditor_uploader.fields.RichTextUploadingField(max_length=1024, verbose_name='制作方法')),
                ('genre', models.IntegerField(choices=[(1, '国内'), (2, '国外')], verbose_name='国内外')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairyland.Category', verbose_name='菜品分类')),
            ],
            options={
                'verbose_name': '所有菜品',
                'verbose_name_plural': '所有菜品',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='地区菜名')),
            ],
            options={
                'verbose_name': '地区菜式',
                'verbose_name_plural': '地区菜式',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分段时间名')),
            ],
            options={
                'verbose_name': '分段时间',
                'verbose_name_plural': '分段时间',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairyland.District', verbose_name='地区菜式'),
        ),
        migrations.AddField(
            model_name='dish',
            name='meal',
            field=models.ManyToManyField(to='fairyland.Meal', verbose_name='适合时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairyland.Dish', verbose_name='评论对象'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
    ]
