# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairyland', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img_sm',
            field=models.ImageField(default='avator/img_sm_404.jpg', upload_to='avator/dishes_thumb/', verbose_name='菜品小图'),
        ),
    ]
