# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairyland', '0002_dish_img_sm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(default='avator/img_404.jpg', upload_to='avator/dishes/', verbose_name='菜品大图'),
        ),
    ]
