# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-03 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190830_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator_sor',
            field=models.ImageField(default='avator/default.jpg', upload_to='avator/uc/', verbose_name='头像'),
        ),
    ]
